CREATE TABLE MerchantInfo
        (
        MERCHANTID VARCHAR(100) PRIMARY KEY NOT NULL,
        NAME VARCHAR(500) NOT NULL,
        EMAIL VARCHAR(500),
        PHONE VARCHAR(100)
        );

CREATE TABLE Menu
(
    MENUID VARCHAR(100) PRIMARY KEY NOT NULL,
    STARTTIME TIMESTAMP NOT NULL,
    ENDTIME TIMESTAMP NOT NULL,
    MERCHANTID VARCHAR(100) NOT NULL,
    FOREIGN KEY (`MERCHANTID`) REFERENCES `MerchantInfo` (`MERCHANTID`)
);

CREATE TABLE CustomerOrder
(
  ORDERID VARCHAR(100) PRIMARY KEY NOT NULL,
  MERCHANTID VARCHAR(100) NOT NULL,
  PRICE INT NOT NULL,
  TIME TIMESTAMP NOT NULL,
  COMMENTS VARCHAR(500),
  CUSTOMERID VARCHAR(100) NOT NULL,
  STATUS VARCHAR(100) NOT NULL,
  FOREIGN KEY (`MERCHANTID`) REFERENCES `MerchantInfo` (`MERCHANTID`),
  FOREIGN KEY (`CUSTOMERID`) REFERENCES `Customer` (`CUSTOMERID`)
);

CREATE TABLE Customer
(
    CUSTOMERID VARCHAR(100) PRIMARY KEY NOT NULL,
    NAME VARCHAR(500) NOT NULL,
    PHONE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL
);

CREATE TABLE ItemForOrder
(
    ITEMID VARCHAR(100) PRIMARY KEY NOT NULL,
    ITEMDESC VARCHAR(500),
    PRICE INT NOT NULL,
    ORDERID VARCHAR(100) NOT NULL,
    FOREIGN KEY (`ORDERID`) REFERENCES `CustomerOrder` (`ORDERID`)
);

CREATE TABLE Item
(
   ITEMID VARCHAR(100) PRIMARY KEY NOT NULL,
   ITEMDESC VARCHAR(1000),
   AVAILABLE TINYINT NOT NULL,
   PRICE INT NOT NULL,
   MENUID VARCHAR(100),
   FOREIGN KEY (`MENUID`) REFERENCES `Menu` (`MENUID`)
);